services/go/api-golang: &api_golang
  - "services/go/api-golang/**"
  - "services/other/api-golang-migrator/**"
  - ".github/workflows/my-test.yaml"

services/node/api-node:
  - "services/node/api-node/**"
  - ".github/workflows/my-test.yaml"

services/other/api-golang-migrator:
  - *api_golang

services/python/load-generator-python:
  - "services/python/load-generator-python/**"
  - ".github/actions/setup-dependencies/action.yaml"

services/react/client-react:
  - "services/react/client-react/**"
  - ".github/actions/setup-dependencies/action.yaml"