name: My Update GitOps Manifests

on:
  workflow_dispatch:
    inputs:
      service:
        required: true
        description: service path in repo
        type: choice
        options:
          - services/go/api-golang
          - services/node/api-node
          - services/other/api-golang-migrator
          - services/python/load-generator-python
          - services/react/client-react
      version:
        required: true
        description: deploy version
        type: string
      environment:
        required: true
        description: deploy environment
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  update-manifests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      - name: Install task
        uses: ./.github/actions/setup-dependencies

      - name: Update Manifests
        working-directory: ${{ inputs.service }}
        run: |
          task utils:update-image-tags-service \
            NEW_TAG=${{ inputs.version }} \ 
            ENVIRONMENT=${{ inputs.environment }}

      
      - name: check diff
        run: |
          git diff