name: Release Please

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c    #v4
        with:
          token: ${{ secrets.GHA_CAPSTONE_PAT }}
          config-file:  .github/utils/release-please-config.json
          manifest-file: .github/utils/.release-please-manifest.json
          target-branch: main
